// <auto-generated />
namespace Sergio.Saude.Repositorio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _987875 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_987875));
        
        string IMigrationMetadata.Id
        {
            get { return "201609030023125_987875"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
