// <auto-generated />
namespace Sergio.Saude.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _654546 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_654546));
        
        string IMigrationMetadata.Id
        {
            get { return "201609060012472_654546"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
