// <auto-generated />
namespace Sergio.Saude.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dadosaudeweb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dadosaudeweb));
        
        string IMigrationMetadata.Id
        {
            get { return "201608051450027_dadosaudeweb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
