// <auto-generated />
namespace Sergio.Saude.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _6546546 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_6546546));
        
        string IMigrationMetadata.Id
        {
            get { return "201609030021552_6546546"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
