// <auto-generated />
namespace Sergio.Saude.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class popula : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(popula));
        
        string IMigrationMetadata.Id
        {
            get { return "201608042323394_popula"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
